version: "3.7"

services:
    prometheus:
        container_name: prometheus
        image: prom/prometheus:v2.1.0
        volumes:
            - ./prometheus/:/etc/prometheus/
        #  - prometheus_data:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
        networks:
            - mysql-network
        ports:
            - 9090:9090
        restart: always

    grafana:
        container_name: grafana
        image: grafana/grafana-oss:8.5.14
        user: "472"
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        networks:
            - mysql-network
        volumes:
            - grafana_data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_INSTALL_PLUGINS=natel-discrete-panel,digiapulssi-breadcrumb-panel,yesoreyeram-boomtable-panel
        restart: always

    cadvisor:
        container_name: cadvisor
        image: google/cadvisor
        networks:
            - mysql-network
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        expose:
            - 8080
        ports:
            - "8005:8080"

    mysql-exporter:
        container_name: mysql-exporter
        image: prom/mysqld-exporter:v0.14.0
        networks:
            - mysql-network
        ports:
            - 9104:9104
        depends_on:
            - mysql_db
        environment:
            - DATA_SOURCE_NAME=exporter:exporter@(mysql_db:3306)/
            - --collect.binlog_size
            - --collect.engine_innodb_status
            - --collect.info_schema.innodb_metrics
            - --collect.info_schema.innodb_tablespaces
            - --collect.info_schema.processlist
            - --collect.info_schema.tablestats
            - --collect.info_schema.query_response_time
            - --collect.info_schema.userstats
            - --collect.perf_schema.eventsstatements
            - --collect.perf_schema.eventswaits
            - --collect.perf_schema.file_events
            - --collect.perf_schema.indexiowaits
            - --collect.perf_schema.memory_events
            - --collect.perf_schema.tableiowaits
            - --collect.perf_schema.tablelocks

    mysql_db:
        container_name: mysql_db
        image: mysql:8
        environment:
            MYSQL_DATABASE: "db"
            # Password for root access
            MYSQL_ROOT_PASSWORD: "password"
        volumes:
            - my_db:/var/lib/mysql
            # the init script runs in ascending order, so we rename to 1 and 2 to force
            # database creation first, and then exporter user creation
            - ./scripts/create_database.sql:/docker-entrypoint-initdb.d/1.sql
            - ./scripts/create_exporter_user.sql:/docker-entrypoint-initdb.d/2.sql
        networks:
            - mysql-network
        ports:
            - 3306:3306
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        restart: always

volumes:
    grafana_data: {}
    my_db: {}

networks:
    mysql-network:
        driver: bridge
