global:
    scrape_interval: 5s

scrape_configs:
    - job_name: "mysql_database"
      static_configs:
          - targets: ["mysql-exporter:9104"]

    - job_name: "cadvisor"
      scrape_interval: 5s
      static_configs:
          - targets: ["cadvisor:8080"]
